%YAML:1.0

#========== Dataset ==========#
num_frames: 150
frame_offset: 0

# # KITTI-360
# is_kitti: 0
# gt_path: /home/kodogyu/Datasets/KITTI-360/data_poses/2013_05_28_drive_0000_sync/cam0_to_world.txt

# # perspective image
# left_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_00/data_rect
# right_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_01/data_rect

# # fisheye image
# left_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_02/data_rgb
# right_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_03/data_rgb

# KITTI
is_kitti: 1
gt_path: /home/kodogyu/Datasets/KITTI/dataset/poses/00.txt

left_images_dir: /home/kodogyu/Datasets/KITTI/dataset/sequences/00/image_0
right_images_dir: /home/kodogyu/Datasets/KITTI/dataset/sequences/00/image_1

#========== Camera parameters ==========#
# # KITTI-360
# fx: 788.629315
# fy: 786.382230
# s: 0.0
# cx: 687.158398
# cy: 317.752196

# KITTI
fx: 718.856
fy: 718.856
s: 0.0
cx: 607.1928
cy: 185.2157

#========== Visualize ==========#
display_gt: 1
# display_type:
#   0: pose only (not aligned)
#   1: pose & landmarks
#   2: pose only (aligned with gt)
#   3: realtime visualization (not aligned)
display_type: 1

#========== Feature extraction ==========#
num_features: 3000

# filtering_mode:
#   0: keypoint filtering
#   1: match filtering
filtering_mode: 1
patch_width: 50
patch_height: 50
kps_per_patch: 70

#========== Feature matching ==========#
des_dist_thresh: 0.6

#========== Optimization ==========#
do_optimize: 0
window_size: 3
optimizer_verbose: 0


#========== Test ==========#
calc_reprojection_error: 1
print_conf: 1

