%YAML:1.0

num_frames: 30

# KITTI-360
# perspective image
left_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_00/data_rgb
right_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_01/data_rgb
# fisheye image
# left_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_02/data_rgb
# right_images_dir: /home/kodogyu/Datasets/KITTI-360/data_2d_raw/2013_05_28_drive_0000_sync/image_03/data_rgb

# KITTI
# left_images_dir: /home/kodogyu/Datasets/KITTI/dataset/sequences/00/image_0
# right_images_dir: /home/kodogyu/Datasets/KITTI/dataset/sequences/00/image_1